FLASK_APP=microblog.py
FLASK_DEBUG=1

MAIL_SERVER=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USE_TLS=1
MAIL_USERNAME=apikey
MAIL_PASSWORD=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
MAIL_DEFAULT_SENDER=vova.kuzmenkov0@gmail.com

GOOGLE_APPLICATION_CREDENTIALS=application_default_credentials.json

#ELASTICSEARCH_URL=http://localhost:9200
ELASTIC_PASSWORD=K+DHwWN4W8tKOcDD6Yi0